import { getIconCollections, iconsPlugin } from '@egoist/tailwindcss-icons'
import colors from 'tailwindcss/colors'
import type { Config } from 'tailwindcss'

export default {
  content: ['app/theme/**/*.{js,ts,vue}'],
  theme: {
    colors: {
      current: 'currentColor',
      transparent: colors.transparent,
      white: colors.white,
      black: colors.black,
      gray: {
        0: 'rgb(var(--gray-0) / <alpha-value>)',
        50: 'rgb(var(--gray-50) / <alpha-value>)',
        100: 'rgb(var(--gray-100) / <alpha-value>)',
        200: 'rgb(var(--gray-200) / <alpha-value>)',
        300: 'rgb(var(--gray-300) / <alpha-value>)',
        400: 'rgb(var(--gray-400) / <alpha-value>)',
        500: 'rgb(var(--gray-500) / <alpha-value>)',
        600: 'rgb(var(--gray-600) / <alpha-value>)',
        700: 'rgb(var(--gray-700) / <alpha-value>)',
        800: 'rgb(var(--gray-800) / <alpha-value>)',
        900: 'rgb(var(--gray-900) / <alpha-value>)',
        950: 'rgb(var(--gray-950) / <alpha-value>)',
      },
      red: {
        50: 'rgb(var(--red-50) / <alpha-value>)',
        100: 'rgb(var(--red-100) / <alpha-value>)',
        200: 'rgb(var(--red-200) / <alpha-value>)',
        300: 'rgb(var(--red-300) / <alpha-value>)',
        400: 'rgb(var(--red-400) / <alpha-value>)',
        500: 'rgb(var(--red-500) / <alpha-value>)',
        600: 'rgb(var(--red-600) / <alpha-value>)',
        700: 'rgb(var(--red-700) / <alpha-value>)',
        800: 'rgb(var(--red-800) / <alpha-value>)',
        900: 'rgb(var(--red-900) / <alpha-value>)',
        950: 'rgb(var(--red-950) / <alpha-value>)',
      },
      orange: {
        50: 'rgb(var(--orange-50) / <alpha-value>)',
        100: 'rgb(var(--orange-100) / <alpha-value>)',
        200: 'rgb(var(--orange-200) / <alpha-value>)',
        300: 'rgb(var(--orange-300) / <alpha-value>)',
        400: 'rgb(var(--orange-400) / <alpha-value>)',
        500: 'rgb(var(--orange-500) / <alpha-value>)',
        600: 'rgb(var(--orange-600) / <alpha-value>)',
        700: 'rgb(var(--orange-700) / <alpha-value>)',
        800: 'rgb(var(--orange-800) / <alpha-value>)',
        900: 'rgb(var(--orange-900) / <alpha-value>)',
        950: 'rgb(var(--orange-950) / <alpha-value>)',
      },
      yellow: {
        50: 'rgb(var(--yellow-50) / <alpha-value>)',
        100: 'rgb(var(--yellow-100) / <alpha-value>)',
        200: 'rgb(var(--yellow-200) / <alpha-value>)',
        300: 'rgb(var(--yellow-300) / <alpha-value>)',
        400: 'rgb(var(--yellow-400) / <alpha-value>)',
        500: 'rgb(var(--yellow-500) / <alpha-value>)',
        600: 'rgb(var(--yellow-600) / <alpha-value>)',
        700: 'rgb(var(--yellow-700) / <alpha-value>)',
        800: 'rgb(var(--yellow-800) / <alpha-value>)',
        900: 'rgb(var(--yellow-900) / <alpha-value>)',
        950: 'rgb(var(--yellow-950) / <alpha-value>)',
      },
      green: {
        50: 'rgb(var(--green-50) / <alpha-value>)',
        100: 'rgb(var(--green-100) / <alpha-value>)',
        200: 'rgb(var(--green-200) / <alpha-value>)',
        300: 'rgb(var(--green-300) / <alpha-value>)',
        400: 'rgb(var(--green-400) / <alpha-value>)',
        500: 'rgb(var(--green-500) / <alpha-value>)',
        600: 'rgb(var(--green-600) / <alpha-value>)',
        700: 'rgb(var(--green-700) / <alpha-value>)',
        800: 'rgb(var(--green-800) / <alpha-value>)',
        900: 'rgb(var(--green-900) / <alpha-value>)',
        950: 'rgb(var(--green-950) / <alpha-value>)',
      },
      blue: {
        50: 'rgb(var(--blue-50) / <alpha-value>)',
        100: 'rgb(var(--blue-100) / <alpha-value>)',
        200: 'rgb(var(--blue-200) / <alpha-value>)',
        300: 'rgb(var(--blue-300) / <alpha-value>)',
        400: 'rgb(var(--blue-400) / <alpha-value>)',
        500: 'rgb(var(--blue-500) / <alpha-value>)',
        600: 'rgb(var(--blue-600) / <alpha-value>)',
        700: 'rgb(var(--blue-700) / <alpha-value>)',
        800: 'rgb(var(--blue-800) / <alpha-value>)',
        900: 'rgb(var(--blue-900) / <alpha-value>)',
        950: 'rgb(var(--blue-950) / <alpha-value>)',
      },
    },
    fontFamily: {
      'sans': ['"Poppins"', 'ui-sans-serif', 'sans-serif'],
    },
  },
  plugins: [
    iconsPlugin({
      collections: getIconCollections(['tabler']),
    }),
  ],
  darkMode: 'class',
} satisfies Config
